/* 星火平台 Demo — 模拟数据（对应 PRD 第 5 章数据模型） */
window.SEED = {
  user: { name: "张浩", open_id: "ou_demo_zhanghao", dept: "产品中心-体验设计部", avatar: "🧑‍💻", avatarImg: "avatars/zhanghao.jpg" },

  tools: [
    { id: 1, av: "avatars/chenxiao.jpg", rate: 4.9, g: ["#FF9500","#FF5E3A"], ic: "receipt-text", name: "发票信息提取工具", type: "网页应用", agent: false,
      desc: "电子发票文件夹拖入即自动提取金额、抬头、日期、税号，生成报销 Excel；低置信行标红可核对。替代每月一整天的手工录入。",
      usage: "第一步：下载并解压 zip；第二步：双击打开 发票提取工具.html；第三步：把发票文件夹拖进虚线框；第四步：核对标红行后点「导出报销表」。",
      tags: ["数据处理", "发票", "报销"], owner: "陈晓", dept: "财务部", date: "2026-06-28",
      env: "零依赖，浏览器双击即用", source: "教练制作回流", status: "已上架",
      reuse: 132, likes: 45, favs: 21,
      comments: [
        { user: "刘洋", dept: "财务部", text: "上月 100 多张发票 10 分钟搞定，太救命了", time: "2026-07-02", likes: 12 },
        { user: "赵蕾", dept: "供应链管理部", text: "税号识别很准，希望支持扫描件", time: "2026-07-08", likes: 5 },
      ] },
    { id: 2, av: "avatars/sunhaoran.jpg", rate: 4.7, g: ["#5AC8FA","#007AFF"], ic: "newspaper", name: "周报汇总工具", type: "网页应用", agent: false,
      desc: "把各部门周报文档拖入，自动汇总成一张 Excel 总表（部门/进展/风险/下周计划），检查一遍即可上交。",
      usage: "第一步：双击打开 周报汇总.html；第二步：拖入周报文档；第三步：点「生成总表」核对后导出。",
      tags: ["数据处理", "周报", "汇总"], owner: "孙浩然", dept: "综合管理部", date: "2026-06-15",
      env: "零依赖，浏览器双击即用", source: "教练制作回流", status: "已上架",
      reuse: 103, likes: 38, favs: 17, comments: [] },
    { id: 3, av: "avatars/linxiaowan.jpg", rate: 4.8, g: ["#FFCC00","#FF9500"], ic: "folder-pen", name: "素材文件批量重命名工具", type: "网页应用", agent: false,
      desc: "拍摄素材按「日期-项目-序号」规则批量重命名，支持预览确认，告别一个个 F2。",
      usage: "第一步：双击打开工具页面；第二步：拖入素材文件夹；第三步：确认预览后点「开始重命名」。",
      tags: ["文件批处理", "素材管理"], owner: "林小婉", dept: "市场部", date: "2026-07-05",
      env: "零依赖，浏览器双击即用", source: "平台手动上传", status: "已上架",
      reuse: 91, likes: 27, favs: 12, comments: [] },
    { id: 4, av: "avatars/zhanghao.jpg", rate: 4.6, g: ["#AF52DE","#5856D6"], ic: "chart-line", name: "竞品价格监控 Skill", type: "Skill", agent: true,
      desc: "每天自动检索主要竞品的电商价格与促销变化，输出对比表格，替代人工逐站巡查。",
      usage: "第一步：把 skill 文件夹拷贝到 ~/.claude/skills/；第二步：新开会话输入 /price-watch；第三步：按提示配置竞品清单。",
      tags: ["信息检索", "电商", "竞品"], owner: "张浩", dept: "产品中心-体验设计部", date: "2026-07-01",
      env: "需 agent 环境（Codex / Claude Code）", source: "教练制作回流", status: "已上架",
      reuse: 77, likes: 31, favs: 19, comments: [] },
    { id: 5, av: "avatars/emmawu.jpg", rate: 4.8, g: ["#34C759","#30B0C7"], ic: "languages", name: "英文文案润色 Skill", type: "Skill", agent: true,
      desc: "海外社媒/商详文案一键润色，保留品牌术语表，输出三个语气版本供选择。",
      usage: "第一步：拷贝到 skills 目录；第二步：/en-polish + 原文即可。",
      tags: ["内容生成", "翻译", "海外"], owner: "Emma Wu", dept: "海外营销部", date: "2026-06-20",
      env: "需 agent 环境（Codex / Claude Code）", source: "存量工具插件上传", status: "已上架",
      reuse: 66, likes: 24, favs: 9, comments: [] },
    { id: 6, av: "avatars/wangmin.jpg", rate: 4.9, g: ["#FF6482","#FF2D55"], ic: "id-card", name: "工牌卡片生成工具", type: "网页应用", agent: false,
      desc: "上传新员工名单 Excel + 卡片底图，批量生成每人一张欢迎卡片，长名字自动缩排不溢出。",
      usage: "第一步：双击打开 工牌卡片生成工具.html；第二步：左框拖名单、右框拖底图；第三步：点「生成全部卡片」后打包下载。",
      tags: ["内容生成", "图片", "HR"], owner: "王敏", dept: "人力资源部", date: "2026-07-12",
      env: "零依赖，浏览器双击即用", source: "教练制作回流", status: "已上架",
      reuse: 58, likes: 23, favs: 8, comments: [] },
    { id: 7, av: "avatars/zhanghao.jpg", rate: 4.7, g: ["#00C7BE","#30B0C7"], ic: "table", name: "门店销售 CSV 汇总工具", type: "网页应用", agent: false,
      desc: "把多个门店的销售 CSV 一键合并成带门店列的总表，自动核对行数与金额合计。",
      usage: "第一步：双击打开工具；第二步：把各门店 CSV 一起拖入；第三步：核对合计后导出总表。",
      tags: ["数据处理", "CSV", "销售"], owner: "张浩", dept: "产品中心-体验设计部", date: "2026-07-21",
      env: "零依赖，浏览器双击即用", source: "教练制作回流", status: "已上架",
      reuse: 46, likes: 18, favs: 7, comments: [] },
    { id: 8, av: "avatars/zhoutiancheng.jpg", rate: 4.5, g: ["#5856D6","#3634A3"], ic: "scale", name: "出货对账机器人", type: "脚本", agent: false,
      desc: "自动比对发货单与回款表，几千行数据秒级找出对不上的订单，输出差异清单。",
      usage: "第一步：把两份表放进 input 文件夹；第二步：双击 run.command；第三步：在 output 查看差异清单。",
      tags: ["数据处理", "对账", "财务"], owner: "周天成", dept: "财务部", date: "2026-06-10",
      env: "需 Python 3（附一键安装说明）", source: "存量工具插件上传", status: "已上架",
      reuse: 41, likes: 15, favs: 6, comments: [] },
    { id: 9, av: "avatars/laoli.jpg", rate: 4.6, g: ["#63E6BE","#20C997"], ic: "mic", name: "周会纪要生成脚本", type: "脚本", agent: false,
      desc: "把周会录音转写文本整理成结构化纪要（议题/结论/待办），支持飞书妙记导出格式。",
      usage: "第一步：转写文本放进 input；第二步：双击 run.command；第三步：output 里拿纪要。",
      tags: ["内容生成", "会议纪要"], owner: "老李", dept: "市场部", date: "2026-07-17",
      env: "需 Python 3（附一键安装说明）", source: "存量工具插件上传", status: "已上架",
      reuse: 34, likes: 11, favs: 4, comments: [] },
    { id: 10, av: "avatars/hejiayin.jpg", rate: 4.4, g: ["#4DABF7","#228BE6"], ic: "headset", name: "客服问题分类统计表", type: "表格模板", agent: false,
      desc: "客服问题登记 + 自动分类统计 + 周报图表一体的多维表格模板，复制即用。",
      usage: "第一步：打开模板链接点「复制」；第二步：按说明填写登记表；第三步：统计视图自动更新。",
      tags: ["数据处理", "客服", "模板"], owner: "何佳音", dept: "用户服务部", date: "2026-05-30",
      env: "飞书多维表格，复制即用", source: "平台手动上传", status: "已上架",
      reuse: 29, likes: 9, favs: 5, comments: [] },
    { id: 11, av: "avatars/wudi.jpg", rate: 4.8, g: ["#B197FC","#845EF0"], ic: "calculator", name: "项目 ROI 快算器", type: "表格模板", agent: false,
      desc: "输入投入与预期收益，自动算 ROI 与回本周期，附敏感性分析。",
      usage: "复制模板后按黄色单元格填写即可。",
      tags: ["数据处理", "财务分析"], owner: "吴迪", dept: "战略投资部", date: "2026-07-20",
      env: "飞书多维表格，复制即用", source: "平台手动上传", status: "待审核",
      reuse: 0, likes: 0, favs: 0, comments: [] },
    { id: 12, av: "avatars/zhengshuang.jpg", rate: 4.7, g: ["#FFA94D","#FF922B"], ic: "calendar-clock", name: "会议室快订 Skill", type: "Skill", agent: true,
      desc: "一句话订会议室：解析时间人数，自动查空闲并预订，冲突时给三个备选。",
      usage: "拷贝到 skills 目录后 /book-room + 需求即可。",
      tags: ["流程审批", "行政"], owner: "郑爽", dept: "综合管理部", date: "2026-07-21",
      env: "需 agent 环境 + 日历权限", source: "教练制作回流", status: "待审核",
      reuse: 0, likes: 0, favs: 0, comments: [] },
  ],

  tickets: [
    { id: "T-2026-018", title: "供应商发票扫描件 OCR 录入", desc: "纸质/扫描发票没法用现有发票工具，每月约 60 张仍要手录。",
      freq: "每月4次", minutes: 120, people: 3, urgency: "中", status: "制作中", owner: "赵蕾", dept: "供应链管理部",
      date: "2026-07-10", linkedTool: null },
    { id: "T-2026-015", title: "海外评论舆情日报", desc: "各平台差评要人工翻找汇总，希望每天自动出一份日报。",
      freq: "每天1次", minutes: 90, people: 2, urgency: "高", status: "已结单", owner: "Emma Wu", dept: "海外营销部",
      date: "2026-06-22", linkedTool: 5 },
  ],

  /* 数据看板（对应 5.3/5.6 聚合口径） */
  dashboard: {
    savedHours: 1286, coveredUsers: 214, buildSessions: 47, buildSuccessRate: 0.83, avgQuestions: 2.4, uploadRate: 0.71,
    deptHours: [
      { dept: "财务部", hours: 342 }, { dept: "产品中心", hours: 296 }, { dept: "市场部", hours: 231 },
      { dept: "人力资源部", hours: 173 }, { dept: "供应链管理部", hours: 128 }, { dept: "其他部门", hours: 116 },
    ],
    reuseTrend: [8,11,9,14,12,10,16,15,13,18,17,14,20,22,19,17,24,21,26,23,25,28,24,27,31,29,26,33,30,36],
  },
};
